### ISSUE TITLE
Configuration problem on Mac

### ISSUE THREAD

**Issue by jeroenk** [mc-imperial/gvki#1]
When trying to configure the interceptor on Mac, I get the following:

```
CMake Error at cmake/findopencl/FindOpenCL.cmake:95 (message):
  Could not find OpenCL header file in
  /System/Library/Frameworks/OpenCL.framework/OpenCL/cl.h
Call Stack (most recent call first):
  CMakeLists.txt:15 (find_package)
```

The header files are in a different a different location on my current system (`/System/Library/Frameworks/OpenCL.framework/Headers`). I'm not sure if this was different in the past. However the proper way to include the header files is to specify `-framework OpenCL` when compiling and using`#include <OpenCL/cl.h>`.

**Comment by delcypher** [comment]
I presume `-framework OpenCL` implies linking against OSX's OpenCL library. I don't want to do that.

I'll just try to fix the `FindOpenCL.cmake` file. Could you clarify what the path to OpenCL headers are

```
/System/Library/Frameworks/OpenCL.framework/Headers/cl.h
```

or

```
/System/Library/Frameworks/OpenCL.framework/Headers/OpenCL/cl.h
```

or something else?

**Comment by jeroenk** [comment]
So:
- The OpenCL header should be included with `#include <OpenCL/cl.h>`
- Currently `cl.h` is located in `/System/Library/Frameworks/OpenCL.framework/Headers` (thus, without `OpenCL`)
- `-framework OpenCL` is only needed for linking; the OpenCL header is picked up irrespective of this.

To me it seems that the autotools way of going over this, i.e., seeing whether a small program including the header actually compiles, might be the easiest way to figure out whether the headers are present on OSX.

**Comment by delcypher** [comment]
The autotools way of going about this probably is the better thing to do.

For now I've commited 8be3485a457d5bad49ef47ddf6bdc5d5ef8bfd1d . Does that fix configuring for you?

**Comment by jeroenk** [comment]
It configures, but now fails at the linking stage:

```
Linking CXX shared library libGVKI_preload.dylib
Undefined symbols for architecture x86_64:
  "_clGetKernelInfo", referenced from:
      gvkiSetupKernelArguments(_cl_kernel*, gvki::KernelInfo&) in InterceptedHostFunctions.cpp.o
      _clCreateKernelsInProgram in InterceptedHostFunctions.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libGVKI_preload.dylib] Error 1
make[1]: *** [lib/CMakeFiles/GVKI_preload.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by delcypher** [comment]
That's weird. I'm not sure why your linker is checking for undefined symbols where as the linker on Linux doesn't seem to care. It is a preload library so there will be missing symbols. If you comment out my use of `clGetKernelInfo()` can you successfully compile and link?

I think this may be the only OpenCL function that I call directly so I should probably fix it so I call it indirectly via a function pointer like I do for all the other OpenCL host calls.

**Comment by jeroenk** [comment]
Try passing `-Wl,-undefined,dynamic_lookup` to the linker on OSX.

**Comment by delcypher** [comment]
Using linker flags is one option but it's cleaner if I just call `clGetKernelInfo()` indirectly like gvki does with all other OpenCL host code calls.

I've implemented that in 6762ec621ebdd628facd85ac8f36016ed239425b . Can you compile and link now?

**Comment by jeroenk** [comment]
Compiles now. Running `make check` gives me 0 failures. Am I correct to think that this tests the dynamic version of interception library?

**Comment by delcypher** [comment]
It tests both the macro and the preload library if you build under Linux or OSX. Under windows it should just test the macro library although I've never tested this.

If you look in the build directory after running `make check` you'll see folders like

```
tests/<test_name>/gvki_macro.log.d/
tests/<test_name>/gvki_preload.log.d/
```

where `<test_name>` is name of a test e.g. `HelloWorldMultipleInvocations`.

These folders contain the `gvki-<N>` folders generated during testing.

The testing is far from complete but at least there are some. Getting 0 failures from `make check` means at the least the basic stuff is working.

**Comment by jeroenk** [comment]
Ok, then this seems fixed.
