### ISSUE TITLE
Give the user the ability to specifiy the output directory

### ISSUE THREAD

**Issue by jeroenk** [mc-imperial/gvki#3]
In large interception on multiple programs, it would be convenient to specify the output directory for interception, to save from having to do manual copying.

**Comment by delcypher** [comment]
This can be already sort of done using the `GVKI_ROOT` environment variable. This sets the directory that the `gvki-<N>` folders are created in.

Do you want to control the name of the `gvki-<N>` folder?

**Comment by jeroenk** [comment]
Indeed, I would like to control the name of the folder.

**Comment by delcypher** [comment]
@jeroenk It's certainly do able. I've tried doing this in bc67f9f3bd386f8bb7c4fe9bc36a3a4751d150a7 but I've not had time to test it. See the `README.md` file for how to use it.

**Comment by jeroenk** [comment]
Thanks, I'll try this at some later date. At least I can report now that we have this feature.

**Comment by jeroenk** [comment]
This doesn't quite work, as I need to create directory manually. It should be created automatically.

**Comment by delcypher** [comment]
@jeroenk I just tried this. There was a bug in my implementation. It should of just crashed if you tried using it (due to NULL pointer dereference) but it's fixed now. It should create the directory for you. Here's an example of using it

```
$ GVKI_NO_NUM_DIRS=1 GVKI_ROOT=`pwd`/mydir ./HelloWorld_gvki_macro
...
$ ls mydir/
hello_kernel.0.cl  log.json
```

**Comment by jeroenk** [comment]
Thanks, this works.

I think that part of the reason it wasn't crashing was that I did:

```
export GVKI_NO_NUM_DIRS
```

while you expected

```
export GVKI_NO_NUM_DIRS=1
```

**Comment by delcypher** [comment]
Well technically all I expect `GVKI_NO_NUM_DIRS` to be any non-empty string. The environment variable names probably should be renamed at some point because this was just a hack. Giving `GVKI_ROOT` two different meanings based on how another environment variable is set is confusing.

But glad it works now.

Closing.
