### ISSUE TITLE
NULL value for local_size is ignored

### ISSUE THREAD

**Issue by jeroenk** [mc-imperial/gvki#4]
If gvki encounters a NULL value for the local_size parameter, it assumes the local size to be equal to the global_size. This is incorrect.

We could change the local size to be equal to `*` in each dimension. It should be easy to have GPUVerify JSON interface support this, as the related command line arguments already do.

**Comment by delcypher** [comment]
```
local_work_size can also be a NULL value in which case the OpenCL implementation will
determine how to be break the global work-items into appropriate work-group instances.
```

Looks like I made the wrong choice. Would assuming that each work item is in its own work group be sound? That means no thread can synchronise with any other thread which would probably be the worst case in terms of "racey-ness". Although I suppose  if the kernel reads `get_local_id()` or `get_local_size()` then we'd miss potentially different behaviour based on the work group size.

Perhaps just emitting that the local size is unconstrained is the best thing to do.

**Comment by jeroenk** [comment]
```
Would assuming that each work item is in its own work group be sound?
```

That would be less sound than what you're doing now, as this means no races on `__local` arrays can occur.

**Comment by delcypher** [comment]
This has been implemented by
- 8c8e674a5317aebcab5225e564e907413b9d17b4
- 89b1b50167c277071a21b08b9886235efabf62d7

If the `local_size` is unconstrained GVKI will emit an array for local_size where each value in array is a string "*". The length of the `local_size` array will match the size of the `global_size` array.

Example:

```
"global_size": [ 2, 2, 2]
"local_size": ["*","*","*"];
```

I don't have to emit "*" however. It simplifies GPUVerify's json parser I could emit `null` instead.

**Comment by jeroenk** [comment]
Let me figure out what is easiest on the side of GPUVerify.

**Comment by delcypher** [comment]
@jeroenk . You can find the current [reference output here](https://github.com/mc-imperial/gvki/tree/master/tests/HelloWorldUnconstrainedLocalSize/reference-output).

**Comment by jeroenk** [comment]
Yeah, let's just omit local_size. That'll result in a cleaner interface.

**Comment by delcypher** [comment]
Except things could go horribly wrong if there was ever a bug in GVKI (or another tool) that meant that `local_size` was not emitted. Currently `local_size` must be specified but this change would make it optional.

If you think it is worth accepting the risk for an improved interface then I'll make the change to GVKI to not emit `local_size` when it is unconstrained.

**Comment by jeroenk** [comment]
The only think that can go horribly wrong is that this might result in false positives or time outs. I think that is acceptable.

**Comment by delcypher** [comment]
Okay. I've implemented this in ae270ec0ee297889ce1498445d5a89e1f9a7a1d7

**Comment by jeroenk** [comment]
Thanks. I've pushed the related change to GPUVerify.

**Comment by afd** [comment]
Thanks for this.

A
